set(_CATKIN_CURRENT_PACKAGE "decision")
set(decision_VERSION "0.0.0")
set(decision_MAINTAINER "ros <ros@todo.todo>")
set(decision_PACKAGE_FORMAT "2")
set(decision_BUILD_DEPENDS "rospy" "std_msgs" "message_generation")
set(decision_BUILD_EXPORT_DEPENDS "rospy")
set(decision_BUILDTOOL_DEPENDS "catkin")
set(decision_BUILDTOOL_EXPORT_DEPENDS )
set(decision_EXEC_DEPENDS "rospy" "std_msgs" "message_runtime")
set(decision_RUN_DEPENDS "rospy" "std_msgs" "message_runtime")
set(decision_TEST_DEPENDS )
set(decision_DOC_DEPENDS )
set(decision_URL_WEBSITE "")
set(decision_URL_BUGTRACKER "")
set(decision_URL_REPOSITORY "")
set(decision_DEPRECATED "")