yolo_model:

  config_file:
    name: rm-yolov3-tiny.cfg
  weight_file:
    name: rm-yolov3-tiny_170000.weights
  threshold:
    value: 0.7
  detection_classes:
    names:
      - blue_enemy
      - red_enemy
